name: Generate contribution snake

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate SVGs
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=%23641020&color_dots=%23f7f1e5,%23f4dfdf,%2355C9EF,%23641020,%23280710
            dist/github-contribution-grid-snake-dark.svg?color_snake=%2355C9EF&color_dots=%23091D36,%23280710,%23641020,%23f4dfdf,%23f7f1e5

      - name: Publish SVGs
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
